import {IProduct} from "../../products-info";

export const forKatepal:IProduct[] = [
  {
    name:"Rocky",
    image:"",
    examples:[],
    description:"",
    parameters:""
  },
  {
    name:"Katrilli",
    image:"",
    examples:[],
    description:"",
    parameters:""
  },
  {
    name:"Ambient",
    image:"",
    examples:[],
    description:"",
    parameters:""
  },
  {
    name:"Jazzy",
    image:"",
    examples:[],
    description:"",
    parameters:""
  },
  {
    name:"Mansion new",
    image:"",
    examples:[],
    description:"",
    parameters:""
  },
  {
    name:"Forte",
    image:"",
    examples:[],
    description:"",
    parameters:""
  },
  {
    name:"Classic KL",
    image:"",
    examples:[],
    description:"",
    parameters:""
  },
  {
    name:"Foxy",
    image:"",
    examples:[],
    description:"",
    parameters:""
  }
]
export const forTechno:IProduct[] = [
  {
    name:"Кадриль",
    image:"",
    examples:[],
    description:"",
    parameters:""
  },
  {
    name:"Румба",
    image:"",
    examples:[],
    description:"",
    parameters:""
  },
  {
    name:"Модерн",
    image:"",
    examples:[],
    description:"",
    parameters:""
  },
  {
    name:"Аккорд",
    image:"",
    examples:[],
    description:"",
    parameters:""
  },
  {
    name:"Соната",
    image:"",
    examples:[],
    description:"",
    parameters:""
  },
  {
    name:"Кантри",
    image:"",
    examples:[],
    description:"",
    parameters:""
  },
  {
    name:"Ранчо",
    image:"",
    examples:[],
    description:"",
    parameters:""
  },
  {
    name:"Континент",
    image:"",
    examples:[],
    description:"",
    parameters:""
  }
]
export const forDoke:IProduct[] = [
  {
    name:"Саппоро",
    image:"",
    examples:[],
    description:"",
    parameters:""
  },
  {
    name:"Женева",
    image:"",
    examples:[],
    description:"",
    parameters:""
  },
  {
    name:"Цюрих",
    image:"",
    examples:[],
    description:"",
    parameters:""
  },
  {
    name:"Ницца",
    image:"",
    examples:[],
    description:"",
    parameters:""
  },
  {
    name:"Кёльн",
    image:"",
    examples:[],
    description:"",
    parameters:""
  },
  {
    name:"Сота",
    image:"",
    examples:[],
    description:"",
    parameters:""
  },
  {
    name:"Тетрис",
    image:"",
    examples:[],
    description:"",
    parameters:""
  },
  {
    name:"Крона",
    image:"",
    examples:[],
    description:"",
    parameters:""
  },
  {
    name:"Dragon",
    image:"",
    examples:[],
    description:"",
    parameters:""
  }
]
